### ISSUE TITLE
Have Label (and maybe Text Update) be rotated (freely or by 90º steps).

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#132]
Requested by ESS H/W Integration group.

**Comment by kasemir** [comment]
Can you give a concrete example why this is requested?

EDM doesn't support rotation of Label or Textupdate widgets.
BOY doesn't support rotation of Label. It does support rotation of Textupdate, but in a strange way where the overall width/height remains the same rectangle, filled with the background color, only the text inside is rotated. So it's only practical for multiples of 90 degree.

![rotate](https://cloud.githubusercontent.com/assets/1932421/19560261/bc2f7ae2-96a1-11e6-96d6-2c3870d14a37.png)

The display builder supports arbitrary rotations of the Picture widget.
The editor tries to support resizing of the overall bounding box, adapting the size of the image so that it fits inside, with slight differences for "Stretch to Fit" being on/off.

If we support this for the Label and Textupdate, I'd like to limit it to multiples of 90 degrees.

**Comment by claudio-rosati** [comment]
What was requested is having the possibility to have vertical labels, so rotations restricted to ±90º. This will help to keep shorted OPI when the label is used to tag a group of objects.
I'm not really sure if it has sense for a Text Update object too.

**Comment by kasemir** [comment]
Would it still require all multiples of 90 degrees, or would just horizontal (as now) and vertical (rotated 90 degrees counter-clockwise) be sufficient?

**Comment by claudio-rosati** [comment]
I think +90 and -90 should be provided

**Comment by claudio-rosati** [comment]
Kay, have you an idea on why my last changes works well on the stand-alone editor, but not inside CS-Studio (it seems that the SWT integration doesn't handle the D&D image)?

**Comment by kasemir** [comment]
(This is about #133, honouring snap-to-grid while dragging, not label rotations)

Right, you can't depend on the D&D image.
If you check Palette.createWidgetEntries(), it calls WidgetTransfer.addDragSupport( .., icon) with the icon of the widget that's dragged from the palette to the editor pane.
In the standalong editor, you see that.
In the FXCanvas-hosted editor, you get some generic drag icon, not the actual widget icon.

This will likely need to be done by starting a SelectedWidgetUITracker, then moving that as the mouse is dragged.

**Comment by claudio-rosati** [comment]
It seems that the drag view image on FXCanvas is a [known problem](https://bugs.openjdk.java.net/browse/JDK-8089465) not yet resolved. So probably it will in a near future.
