### ISSUE TITLE
Snap to grid still doesn't work

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#133]
Snap to grid still doesn't work properly: when a new object is dropped into the editor both location and size is not initially snapped to grid (initial size snapping can be verified changing the grid size to 11, for example).

**Comment by kasemir** [comment]
Same behaviour as in BOY: When dropping a new widget into the display, it's dropped with its initial size ( #131 ) at the drop location.
From then on, when moving/resizing the widget interactively, the `SelectedWidgetUITracker` (rectangle with handles on the 4 corners and midpoints) will snap to the grid and/or to other widgets.

Somewhat related: When entering specific values for the X, Y, Width, Height properties, they are used as provided without regarding grid or other widgets.

I don't see immediate need to change this behaviour, it's no show stopper for us.
Still, a possible improvement could be this:
When dragging a new widget into the display, the tracker appears right away, and the X/Y coordinate respects the grid and/or other widgets (if grid and/or snap-to-widgets is enabled).
Would be a little more convenient, because eliminates need to select & move each newly dropped widget.
Might be a little tricky to implement. The tracker currently operates on one or more widgets that are selected in the model. To support this new behavioer, the tracker would need to operate on a widget that doesn't actually exist, yet, in the model. It's only the outline of what's dragged in, but hasn't been dropped, and might actually never be dropped.

**Comment by claudio-rosati** [comment]
It should be done as a drag behavior: when entering the editor a possible fake object is inserted and tracked, when exiting (true exit or drop) the fake object is removed and, if drop, the fake object's location is assigned to the new object being inserted.
I need to put hands on the D&D code to handle dropping files, I can see if and how manage also this thing.

**Comment by claudio-rosati** [comment]
I've tried to have more visual feedback, but it works only on stand-alone editor, not inside CS-Studio.

It seems that the drag view image on FXCanvas is a [known problem](https://bugs.openjdk.java.net/browse/JDK-8089465) not yet resolved. So probably it will in a near future.
