### ISSUE TITLE
Invisible Widgets still Visible in Editor (but not selectable)

### ISSUE THREAD

**Issue by ghmegan** [kasemir/org.csstudio.display.builder#158]
When changing a widget visible to "false", the widget does not become invisible in edit mode. The widget will not appear in run mode.

However, once a widget visibility is set to "false" it cannot be selected by clicking, only by selecting the widget name in the outline.

Perhaps the widget should be invisible in edit mode as well as run mode? Or some other option?

**Comment by kasemir** [comment]
It was a silly idea to keep 'invisible' widgets visible in the editor.
In edit mode, they were 'disabled' instead of hidden, but as described the disabled widgets cannot be selected, and one doesn't get the real pre-view when the invisible widgets are still shown.

Updated that to just hide invisible widgets.
They can be selected in the outline, or by rubberbanding a selection that encloses the area of the hidden widget.
