### ISSUE TITLE
RuntimeDemoJavaFX: JythonScriptSupport.init fails

### ISSUE THREAD

**Issue by pavel-ch** [kasemir/org.csstudio.display.builder#188]
I have got the current Display Builder sources successfully compiled according to your instructions in readme.md (I am not a Java expert, though).
When testing Display Builder with RuntimeDemoJavaFX, I have found two issues so far:
1) PVs in tested screens do not work, widgets show PV names instead, with: Exception in thread "DisplayRuntime-2" java.lang.NoClassDefFoundError: gov/aps/jca/event/ConnectionListener. 
I put it to work after explicitly adding the org.csstudio.platform.libs.epics to the run configuration classpath. Is there anything missing in described configuration steps in readme.md?
2) When opening the 10_scripts.bob display, the JythonScriptSupport.init fails with:
2017-01-04 11:14:53 SEVERE [org.csstudio.display.builder.runtime.RuntimePlugin] Once this worked OK, but now the Jython initialization failed. Don't you hate computers?
java.lang.Exception: Cannot locate jython bundle. No OSGi?
	at org.csstudio.display.builder.runtime.script.internal.JythonScriptSupport.init(JythonScriptSupport.java:71)
Can be anything wrong in the configuration, or is it a deeper problem around OSGi?

Thank you for a comment.

Pavel

**Comment by pavel-ch** [comment]
Finally I have been able to make it (python scripts) run. The problem is in missing connect2j module. If I copied this module to the path known to Jython, all is working. 
1. The question remains how to make it run automatically without manual copying.
2. Is it possible (also for the future) to think about usage of the Display Builder in the pure JavaFX application? See my test with jfxtra Window class. This promises many times better UI control fo me than using RCP.
![mdi_test_app](https://cloud.githubusercontent.com/assets/771816/21643613/93ed6cc8-d289-11e6-81f9-c4cd676faafe.PNG)


Thank you for a comment.

**Comment by kasemir** [comment]
* Have to add org.csstudio.platform.libs.epics to the run configuration? Then your development setup must be older. There is no org.csstudio.platform.libs.epics any more. Instead, we use org.epics.jca and org.epics.caj. Looks like you don't have those, thus you got the error, and then you worked around that by including the older org.csstudio.platform.libs.epics which basically wrapped those two jar files?

* connect2j: Yes, this needs to be installed as mentioned in the online help, https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.editor.rcp/doc/display.builder.html. Just like python and py4j need to be installed. Pure jython examples work without those.

* Pure Java FX: I offer the standalone runtime. It still uses OSGi to be able to use plugins, preferences etc. But the UI is plain JavaFX. The maven build creates the display-runtime* products that you see on https://ics-web.sns.ornl.gov/css/display.builder. Main code is in org.csstudio.display.builder.rcp.RuntimeApplication.  The RuntimeDemoJavaFX shows a way to get the runtime without OSGi (and then you get those "Jython initialization failed" errors, but basic Jython scripts still work). I'm personally not interested in pursuing these beyond the "look, this is basically possible" state because for what we need operational, we do like to use this within CS-Studio. See "Display Builder Update" presentation at recent EPICS meeting, https://conference.sns.gov/event/11/contributions, for a comparison of what you get with the standalone runtime and with the CS-Studio integration.

**Comment by kasemir** [comment]
Some detail on the "Jython initialization failed":

When running under OSGi, we locate the Jython plugin, configure the path to the Lib/ in there, and also add the path to the org.csstudio.display.builder.runtime plugin's scripts/ dir for connect2j.

If we don't use OSGi, we have no idea where the Jython Lib/ or connect2j may be, so then you're on your own. See source code of JythonScriptSupport for more on what it's trying to configure as long as it can find Jython as a plugin.

**Comment by willrogers** [comment]
Hi Pavel,

I know I am guilty of ignoring at least one of your suggestions about BOY but I would be interested to know what you think the missing features are.

Could you open a ticket on the main CS-Studio repo briefly listing them?  I might close it if the goals are not achievable for BOY but maybe we could make some improvements.

Cheers,
Will

**Comment by kasemir** [comment]
Yes, we can start with suggestions for BOY.
If they jive with the operational needs of BOY users, they can be implemented there and ported to the display builder. Some may also not be feasible for BOY, but still be possible for the display builder. And on some we might just agree to disagree about their usefulness.

Not knowing what you actually have in mind, I can't tell if that's best discussed via issue tickets or in a hangout.

**Comment by pavel-ch** [comment]
Fine, I prepare some points in few days and comment to the main css repo. I did not follow BOY too much in last months, so I have to look there, too.
