### ISSUE TITLE
DisplayBuilder never opens, blocking the CS-Studio application.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#201]
**Case 1:**
I start CS-Studio. I close all (editor and runtime) windows. I quit CS-Studio and start it again, then I open (double-click) with the DisplayBuilder editor the attached test-01.bob: the application blocks forever.

**Case 2:**
I start CS-Studio and I open any `.bob` file with the DisplayBuilder editor. Then I close that file and I open  (double-click) the attached test-01.bob (that should open). I leave it open and I quit CS-Studio. The I start CS-Studio again and... it stay blocked forever.

[test-01.bob.txt](https://github.com/kasemir/org.csstudio.display.builder/files/732621/test-01.bob.txt)

**Comment by kasemir** [comment]
Cannot reproduce (Linux). Are you seeing that on the Mac? Stack dump?

**Comment by claudio-rosati** [comment]
You're right: it seems to be a Mac problem, not happening on my CentOS.

I've attached the CS-Studio log, the jstack file and the stack frame produced by MacOS X when the application is killed. I hope you'll find something useful.

[css.log.txt](https://github.com/kasemir/org.csstudio.display.builder/files/734780/css.log.txt)
[jstack.log.txt](https://github.com/kasemir/org.csstudio.display.builder/files/734782/jstack.log.txt)
[mstack.log.txt](https://github.com/kasemir/org.csstudio.display.builder/files/734781/mstack.log.txt)

**Comment by kasemir** [comment]
While the jstack log claims "No deadlocks found.", I think there is one:
```
Thread 79923: Background thread for 'tank' widget tries to create a new image:
 - sun.java2d.opengl.CGLGraphicsConfig.getCGLConfigInfo(int, int, int) @bci=0 (Interpreted frame)
..
 - java.awt.image.BufferedImage.createGraphics() @bci=0, line=1181 (Interpreted frame)
 - org.csstudio.javafx.rtplot.RTTank.updateImageBuffer() @bci=39, line=191 (Interpreted frame)
```
```
Thread 775: Main thread also creating a new AWT BufferedImage:
 - java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment() @bci=0, line=81 (Interpreted frame)
 - java.awt.image.BufferedImage.createGraphics() @bci=0, line=1181 (Interpreted frame)
 - org.csstudio.display.builder.representation.javafx.JFXRepresentation.updateBackground() @bci=153, line=667 (Interpreted frame)
..
 - org.csstudio.display.builder.editor.rcp.DisplayEditorPart$$Lambda$362.run() @bci=8 (Interpreted frame)
..
 - org.eclipse.equinox.launcher.Main.run(java.lang.String[]) @bci=4, line=1519 (Interpreted frame)
```

I don't see clear Javadoc on weather creating a BufferedImage and its GC is permitted off the UI thread. We certainly do that a lot, diirt/graphene also uses BufferedImages to prepare graphics on background threads, then later using the UI thread to show the Buf.Img. on the screen.

If necessary, we could briefly go from the background thread back to the UI thread just to _create_ the buffered image and GC, then do the _drawing_ again in the background.
Would be good to know exactly what the rules are, instead of just trying things...

**Comment by kasemir** [comment]
I was able to reproduce it on Mac OS X, and comitted an update that always creates the BufferedImages on the UI thread. The images are then still drawn off the UI thread to keep the UI responsive.

**Comment by claudio-rosati** [comment]
In theory should be no problem creating a BufferedImage in a non-UI thread (I did it in the past many times without problems). The problem arise if that image is (partially) created or updated in a thread while the UI one is trying to display it.

In practice the problem existed and you fix is working. I close this issue.

**Comment by kasemir** [comment]
To clarify, this deadlock is not about thread 1 drawing a BufferedImage while thread 2 is already using that same BufferedImage. The display buillder code completely creates and draws the image on thread 1 before making it visible to thread 2.

The deadlock shows two threads (one background thread and the UI thread) concurrently doing this:
```
BufferedImage img = new BufferedImage(..);
Graphics gc = img.createGraphics();
```
They deadlock because `createGraphics` accesses some global UI lock, at least in the Mac OS X implementation.

**Comment by claudio-rosati** [comment]
Yes, that is what I wanted say with "in practice the problem existed".
All my previous experience was creating off-UI-thread BufferedImages on WIndows and Linux, not on mac. So on mac the problems exists.
