### ISSUE TITLE
"Save" action disabled when the focus is inside the Display Builder's Properties view.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#213]
The Properties view displays the properties of a known Display being edited. "Save" action should be enabled, avoiding the annoying clicking to be first performed inside the Display itself.

**Comment by willrogers** [comment]
I believe this applies to BOY as well.

**Comment by claudio-rosati** [comment]
I've tried on MacOS and CentOS: here there is not this problem for BOY, only Display Builder.

**Comment by willrogers** [comment]
No, it seems you're right.  Perhaps I am mistaken or perhaps this happens occasionally.  I will keep an eye out.

**Comment by claudio-rosati** [comment]
I've tried again and again, and it seems you are right: the problem occurs occasionally on BOY. Most of the time it works weel, sometime not.

**Comment by kasemir** [comment]
I think it's related to https://github.com/ControlSystemStudio/cs-studio/issues/1619 :

We had the problem that you could not close the property view or outline view because they claimed a "dirty" state. So we fixed that by dis-associating those views from the editor. Look for `ISaveablePart` in the data browser, display builder, BOY, ..

The downside may be that they're now dis-associated from the editor and don't know how to save anything.

**Comment by claudio-rosati** [comment]
I think this is a very annoying behaviour.

**Comment by kasemir** [comment]
Well, here's an update.

The underlying problem is the `ISaveablePart`. My guess is that as RCP started to weaken the distinction between editors and views, anything could be moved into the 'editors' section of the screen and views could have a 'dirty' state, but something is missing to refresh the dirty state for views.

Eclipse RCP checks each part if it either is-a or adapts-to `ISaveablePart`. The `ISaveablePart` is then used to check the 'dirty' state, allow Save, SaveAs etc.

We made the property views adapt to `ISaveablePart` and then act as if there's nothing to save to fix  ControlSystemStudio/cs-studio#1619. If you think this issue is annoying behaviour, that was worse: Close the property view (not the editor!) and you get a "do you want to save" dialog. Or close CSS, and you get __two__ "do you want to save" dialogs, one for the editor and one for the property view.

For the display builder I've now tried something else, which I think is overall better:
The property view implements `ISaveablePart`, forwarding operations to the editor, except for `isSaveOnCloseNeeded()` returning false.

Now all this is good:

Open editor, open property view, open outline view.
Change anything in editor, editor is "dirty"
Invoking File/Save or pressing Ctrl-S in either editor, property view (as you wanted), or outline view saves the file and clears the editor's "dirty" state.

You can always close the property view, it won't prompt for "do you want to save" (i.e. we're still fixing bug 1619).
Closing the dirty editor will of course still prompt "do you want to save".

Only remaining quirk:
Close property view, change anything in editor, open property view.
The property view now has the "*" dirty mark in its title tab.
Save the editor via File/Save or pressing Ctrl-S in either editor, property view, or outline view.
-> File is saved, editor no longer dirty, but property view remains dirty.

So the remaining issue is that you can end up with an erroneous "*" in the property view title tab.

**Comment by claudio-rosati** [comment]
I think this is much better tahn before.
Thank you Kay
