### ISSUE TITLE
DataBrowser 2 vs 3

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#225]
Hello Kay,

I would like to know the difference between DataBrowser 2 and 3.
I've enabled on my CS-Studio DB3 and it seems to me identical to the old one (also because the icon is the same and they canno be distinguished fron the tab icon).
Is DB3 substituting the old one? Have I to remove the old one from my product?

Claudio

**Comment by kasemir** [comment]
Databrowser2 uses the SWT-based plot. It comes with databrowser2.opiwidget as a BOY widget. There is no display builder widget, since it's SWT.

Databrowser3 uses the JavaFX-based plot. It naturally comes with a display builder widget, and there's also a BOY widget.

Databrowser3 uses the same IDs for its editor as DB2. The idea was that existing workspaces that had DB2 open, then update to a new version of CSS, would still open that same data browser configuration. This does mean, however, that you cannot have both DB2 and DB3 in the same product. The preference settings, unfortunately, need to use o.c.trends.databrowser3/.. as a prefix because otherwise Eclipse would still look for the defaults in a DB2 plugin, which isn't there anymore in an updated product.

At the SNS we now include DB3 in the product, removing DB2, even on beam lines that still use BOY.
For beam lines that use the display builder, DB3 is of course the only viable choice.

**Comment by claudio-rosati** [comment]
Thank you.
I've removed from my product the dependency with databrowser2 in favour of the new one. It works nicely.

Have you plans to add a DataBrowser widget also for Display Builder?

**Comment by kasemir** [comment]
The DataBrowser widget for the Display Builder is in o.c.trends.databrowser3.bobwidget(.feature).

**Comment by claudio-rosati** [comment]
Oh oops,
I've added the feature but I've not checked display builder for the widget. 
I'll do on Monday. Thank you
Have a nice weekend
