### ISSUE TITLE
Add the possibility to run a .bob file in a stand-alone window.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#271]
Colleagues here at ESS started to use Display Builder instead of BOY. One of the more frequently requested thing is to be able to run the `.bob` file in a stand-alone window.

**Comment by kasemir** [comment]
When you have a display runtime in RCP with an Action Button to open another display, you can already SHIFT-CTRL-click on the action button to open the related display in a standalone JFX Stage.

.. and it will generally execute a bit faster that way, or the CPU load will be lower when you check jvisualvm.

But that standalone window has the same issues as the BOY standalone window: You can't move it back into the workbench, there's no context menu, no toolbar etc.
So once people open the standalone windows, I bet you next need to add context menu, then spend time on the equivalent of  the standalone window manager in BOY.
Instead of implementing a portion of RCP for RCP, I'd rather work on the Phoebus framework.

**Comment by willrogers** [comment]
You do have context menu in the standalone window.

Kay's general point stands, I think.

**Comment by claudio-rosati** [comment]
@kasemir 
This problem is getting more urgent with more users of Display Builder at ESS.

- Detaching a runtime display will create a window with the wrong size;
- As in BOY, people is expecting 2 ways of launching the runtime from a `.bob` file in the Navigator or from the context menu in editor: execute in workbench or execute in stand-alone window;
- Even if SHIFT-CTRL-click on an action button can open the related display in a standalone JFX Stage, users would have it as a specific action (again, open display in workbench or in stand-alone window).

I don't have problems to implement it: can you just give me few hints on where start looking for?

**Comment by kasemir** [comment]
Do you want to offer the Shift-Ctrl-click behavior from an action, so the action editor allows configuring "Standalone"
-> Set org.csstudio.display.builder.model/support_standalone_window=true

**Comment by claudio-rosati** [comment]
@kasemir 
I've set the preference to true, and now I can set an action to open a secondary OPI on a stand-alone window.

This doesn't solve the various problems still related to opening an OPI in stand-alone mode. I summarise them here:

- When an action is set to open an OPI in a new Workbench window, that window is not sized to correctly display the whole OPI (as defined by the Display width and height);
- It is not possible to open in a stand-alone window (workbench or not) from the Navigator window (there only a single option available: Display Runtime);

<img width="483" alt="stand-alone-01" src="https://user-images.githubusercontent.com/10833922/36466681-9d68b54a-16db-11e8-862a-1b3a634f7c66.png">

- It is not possible to open in a stand-alone window (workbench or not) from the Editor window (there only a single option available: Execute Display).

<img width="262" alt="stand-alone-02" src="https://user-images.githubusercontent.com/10833922/36466847-5b5ee6a0-16dc-11e8-8751-9db4be759d8a.png">

**Comment by kasemir** [comment]
> .. new Workbench window, that window is not sized to correctly display the whole OPI (as defined by the Display width and height)

Feel free to fix that. Looks at `RCP_JFXRepresentation#openNewWindow` or `RCP_JFXRepresentation#openStandaloneWindow`.

> not possible to open in a stand-alone window (workbench or not) from the Navigator window (there only a single option available: Display Runtime);

Not sure this is a practical issue for an operational setup.
Control room operators should not need to browse the file system (or navigator) for display files. Instead, the top displays list includes one or more start pages, which then link to all the rest. Any of those links offer some control over the page handling (replace, open new tab, .., limited by RCP).

The technical issue is that the context menu entries are added via contributions from the plugin.xml. You can't easily show/hide them based on a preference setting. So sites which don't want to support the standalone windows (because they don't participate in the perspective handling) wouldn't have a way to hide them.

**Comment by claudio-rosati** [comment]
> Not sure this is a practical issue for an operational setup...

OK, I understand your point. The thing I'm still in trouble now is related to the "top displays list ": imagine I have 3 screens and I would like to have in one (e.g. the left one) CS-Studio workbench with a runtime OPI, and 2 stand-alone windows fitting the remaining screen each. Is that possible? If yes, how can I tell it to CS-Studio?

**Comment by kasemir** [comment]
The closest I've come to that is using perspectives:

Start CSS with new workspace.
Use display runtime perspective, position on first monitor.
Open displays, dragging some of them out into second or third monitor.
Save as named perspective.

That way you can save layouts that span several monitors, and switch between them.
Users do need to close unused perspectives because otherwise a perspective once opened keeps using some CPU and memory.

**Comment by pavel-ch** [comment]
I recommend to implement a parameterized Open Display action, minimally for the use from Action Buttons and Scripts (give (eventually macroized) absolute or relative X Y, and W H). This can solve a lot of issues, and is not in conflict with perspectives, which restores a frozen known state only.

**Comment by claudio-rosati** [comment]
Thank you Kay.

> Users do need to close unused perspectives because otherwise a perspective once opened keeps using some CPU and memory.

That's a very interesting information!

**Comment by claudio-rosati** [comment]
#358 fixes the following:

> Detaching a runtime display will create a window with the wrong size

This was the main issue for ESS. Can we close the issue?
