### ISSUE TITLE
Rules and Scripts dialogs issues

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#286]
- When a new rule/script is created, it should be selected and the editor opened to quickly change its name.
- When a new PV is added, it should be selected and the editor opened to quickly change its name.
- When a new espression is added, it should be selected and the editor opened to quickly change the espression.

**Comment by claudio-rosati** [comment]
@kasemir A colleague also pointed out the following:

- If a script dialog is opened (the first time, so no scripts already exist) all PV-related buttons are enabled and can be acted on.

![image001](https://user-images.githubusercontent.com/10833922/34868497-4575c394-f784-11e7-8f61-2cbbbe35faeb.jpg)

- If a script is added, it is not initially selected (see previous comment). If it is not selected all PV-related buttons are enabled and can be acted on.

![image007](https://user-images.githubusercontent.com/10833922/34868559-8188bcd8-f784-11e7-8a98-ec7e8686f07e.jpg)

This way all the PVs someone adds are not stored!

The solutions seems to be:

- Select automatically a script (or rule) when created;
- Make PV-related buttons disabled when a script (or rule) is not selected.

**Comment by claudio-rosati** [comment]
A further problem indicated by the same colleague.

> If I add a PV anywhere in a window (Scrip, Rule, etc.) I type the PV name and I press ENTER. After this the active button is on the Cancel button in the bottom left corner, so If I press two Enter after the PV name the whole work I have made is lost. Is it possible to select the OK after leaving the PV field?

**Comment by kasemir** [comment]
Can you work on fixing this?

**Comment by claudio-rosati** [comment]
Yes I will, next week or the following.
In any cases I have other requests on those dialogs.
Before modifying them I'll send you a message about the requested changes in order to agree on them.

**Comment by claudio-rosati** [comment]
@kasemir a question for you:

Why the Rules dialog is in `org.csstudio.display.builder.editor.properties` instead of `org.csstudio.display.builder.representation.javafx` (i.e. why it is not in the same package with the other dialogs)?

P.S.
I've just started working on it. It you think it is worth moving it, tell me and I'll do it.

**Comment by kasemir** [comment]
Because Megan put is there.
Conceptually, it could be in org.csstudio.display.builder.representation.javafx, and an SWT version would then be placed in org.csstudio.display.builder.representation.swt.
In reality, the rules editor, like the scripts, fonts, color, .. dialog, is only used in the _editor_, and for the editor we are not seriously considering an SWT version.
For the runtime, we are also not considering an SWT version, either. If there was a serious issue with JavaFX, we might, however, consider a new org.csstudio.display.builder.representation.whatever, so for the runtime I certainly want to keep the separation of model, runtime and representation.

==> Move the rules dialog to org.csstudio.display.builder.representation.javafx for consistency

**Comment by claudio-rosati** [comment]
I'll do it. Thank you

**Comment by claudio-rosati** [comment]
It's too complex: this class uses a lot of other classes in builder.editor plugin. So for now I leave it in its current location.
