### ISSUE TITLE
Properties bombo box

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#305]
Properties combo box should be reworked because currently any bad string can be inputted and the only effect is to have a error logged in console (something like the following: `Enum property 'skin' expects ordinal but received 'wer'`).

My proposal is:

- Making the combo box not editable: this clearly states that nothing different from the available choices can be selected;
- or validate the user input (possibly with auto completion taken from the available values), where invalid text is written in red (or red background) and, in any case, the previous valid value is retained as soon as the combo box loses the focus.

**Comment by kasemir** [comment]
The editable part of the combo is currently necessary to allow entering macro-based values.

In principle, it should be possible to use the existing `restrictValue()` method, 
https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/WidgetProperty.java#L259,
to check in the editor if an arbitrary value is valid without actually setting the value.
(make the method public, and then try something like
`boolean valid = property.restrictValue(test_value).equals(test_value)`.

But again note that the entered value can be a macro-based text, and the value of the macro is not known at edit time, because the display is meant to be used as an embedded display where the macro values will be provided by the container or caller at runtime.

So the test code would need to allow anything if `MacroHandler.containsMacros(test_value.toString())`.

Since macro-based values are less frequently used than plain values, it would be OK to offer some alternate, switching UI, for example a drop-down of enumerated values or a checkbox for boolean values, plus then some way to change that into a  text entry for entering macro-based values.
Unclear though how that would look & work, how to toggle between the drop-down resp. checkbox and the text entry.

**Comment by claudio-rosati** [comment]
Thank you for the answer, now I understand the problem. I think a solution can be found. I add it to my list of improvements to be done.

**Comment by kasemir** [comment]
The perfect use case that guides this change should be the 'boolean' options (visible, alarm sensitive, ..). In 94.9% of the cases, you don't edit the option at all. In 5% of the widgets, you need to change the value from true to false. In 0.1%, you do need to enter a macro-based value.

They should just have a checkbox, plus then some way to edit a macro-based value for the 0.1% case where you do want to use a macro. A checkbox with a 'pencil' type icon to the right that replaces the checkbox with a text entry would work.

Similar for enumerated values: A drop-down with the options, then a 'pencil' type icon to the right to change into a  text entry where you enter a macro-based value.

**Comment by kasemir** [comment]
Thanks for the update, I've imported it into the phoebus work.
Also modified the bool handling such that there's now just a checkbox for plain boolean properties. A checkbox seems best for 99% of all boolean properties. The editable combo only appears when macros are requested or found in the value.

![mac](https://user-images.githubusercontent.com/1932421/33272131-47e93b16-d357-11e7-888c-c0c715806c7e.png)

**Comment by claudio-rosati** [comment]
Will you port it back to the CS-Studio version of DB?

**Comment by claudio-rosati** [comment]
Sorry, I've just seen now it is already there.
