### ISSUE TITLE
Problems triggering a JS script

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#324]
@kasemir 
Answering a request from a colleague about how to write in console from JS script, I've created (really I've modified an already existing one) an example where the display itself has a script writing in console and triggered by the PV the various widgets use.

A strange string happens: the scripts is triggered only every two changes in the PV. Is it a bug? Did I made an error somewhere in the `.bob` file that justify this behaviour?

[test-js.bob.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1626121/test-js.bob.zip)

**Comment by kasemir** [comment]
When I add a jython script, it's called for every update, but as you observed the jython version only shows output every second time.
Will look into it.

**Comment by kasemir** [comment]
Each display has one script execution queue.
When a script is triggered, it's added to the queue and then executed.
That queue is more like a Set. If a script is triggered rapidly, i.e. triggered again while it's already in the queue, it's not added once more.
For JavaScript, there's some problem that keeps the script in the queue too long, so every other time it's skipped because we think it's already queued, when in fact it shouldn't.

I'll fix it.

**Comment by claudio-rosati** [comment]
OK, thank you.
I'll discovered casually, so I don't think it is an high priority.

**Comment by claudio-rosati** [comment]
Just checked with my example and it works nicely now.
Thank you.
