### ISSUE TITLE
CSSTUDIO-615: Odd behaviour of Embedded Display transparency.

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#360]
I have a small display: on the left a Text Entry with a WriteBackground, on the right a non-transparent Text Update with a ReadBackground. Display color is magenta.

![img1](https://user-images.githubusercontent.com/10833922/37156275-ea255bac-22e5-11e8-8cef-cab2f914e18c.png)

The container has a green background and a transparent Embedded Display.

![img2](https://user-images.githubusercontent.com/10833922/37156333-19c7a252-22e6-11e8-9c12-934fb569cb20.png)

As you can see in the editor, strangely enough the Text Entry background disappeared. The same if you run it.

![img3](https://user-images.githubusercontent.com/10833922/37156394-4bcbab40-22e6-11e8-92ca-16e054bc6f87.png)

If the Embedded Display is made opaque, then still in the editor the Text Entry background is not visible.

![img4](https://user-images.githubusercontent.com/10833922/37156485-811cebe2-22e6-11e8-820b-d91cd1700835.png)

But it will be visible when run.

![img5](https://user-images.githubusercontent.com/10833922/37156542-9f26c0d6-22e6-11e8-8839-70622dd16214.png)

**Comment by claudio-rosati** [comment]
Forgot the OPIs:

[CSSTUDIO-615.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1793541/CSSTUDIO-615.zip)

**Comment by claudio-rosati** [comment]
Moreover, as you can see, when not transparent there is the strange grey area under the Embedded Display.

**Comment by claudio-rosati** [comment]
Thank you Kay

**Comment by kasemir** [comment]
> when not transparent there is the strange grey area under the Embedded Display.

Has that also been resolved? I saw it in your screenshot, but not locally.

**Comment by claudio-rosati** [comment]
@kasemir 
Yes it was also resolved.

**Comment by kasemir** [comment]
Good.

Making the ScrollPane transparent is hard because simply `setBackground(new Background(Color.TRANSPARENT..)` is insufficient. The 'background' is just a small border around the scroll pane, the body of the scroll pane is a `viewport` created in its skin, which you cannot conveniently reach from the source code.
The original code set `fx-background: null`. Not `transparent`, but `null`, which really is an error, so the rendering basically runs into an exception and thus you see no scroll pane. Look as if it's transparent, but is actually damaging the rendering down the scene graph.

**Comment by claudio-rosati** [comment]
Yes, I've seen some CSS-related warning before.

**Comment by kasemir** [comment]
> CSS-related warning

Yes, problem with those tends to be finding the actual style that caused them.
And I don't always get them.
But pretty certain the ones I saw yesterday were caused by `null` for a color.
