### ISSUE TITLE
CSSTUDIO-614: Different macro name convention in BOY and BOB makes very difficult to import BOY files

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#361]
BOY macro names can have '-' character in the name (e.g. `PVi40-PV`). In Display Builder this is not allowed (I cannot add a macro with '-' in the Macros dialog).

This is an issue for our integrators that are requested to port their first OPIs from BOY to Display Builder.

@kasemir 
Is there a reason for not allowing the '-' char?

**Comment by kasemir** [comment]
Macros are stored in the display file as XML tags: `<NameOfMacro>The value</NameOfMacro>`.
Macro names thus must be valid XML names.

This means they must start with a character. Cannot use "9Apples" as a macro name.
I think '-' is OK, but again not as the first character.
Update the MACRO_NAME_PATTERN in https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.model/src/org/csstudio/display/builder/model/macros/Macros.java to allow '-'.

**Comment by kasemir** [comment]
Can you try simply adding "-" to the  MACRO_NAME_PATTERN ?
That should work, unless you do have macros that start with a dash, which is not valid for XML.
Otherwise, the fix would be a more elaborate change in `MacrosWidgetProperty.readFromXML`: For older config files (BOY), patch '-' in the name into underscore, and add a valid XML character to macro names that don't start with a character.

**Comment by claudio-rosati** [comment]
Let me try now

**Comment by kasemir** [comment]
Good, thanks!
