### ISSUE TITLE
Merging Boolean Button and CheckBox widgets

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#410]
It seems to me that Boolean Button and CheckBox widgets are identical in behaviour.

Why not merging them in a single Boolean Button with selectable style? This will allow also adding a new, more modern, iOS-like sliding button style.

**Comment by kasemir** [comment]
Sure, you could combine all buttons into just a button widget with options what it looks like.
Just like all texts could be a text widget, with options to act as a Label, Text Update, Text Entry, .
Or a Circle, boolean LED, multi-state LED could be the same.
Actually, just a Shape widget with option to be square, rect, circle, polyline.

But the idea is to describe the display fairly well, so that existing display files can later be translated to the next tool. With the Display Builder, we even go as far as having a different (Boolean) LED and a Multi-State LED widget because their configuration and behavior differs enough.

Similarly, a checkbox is different enough from a plain button:
Buttons tends to have height, while checkboxes with their label tend to be only as high as the text.
Checkbox is meant to clearly reflect the checked/unchecked state, whereas a button is meant to be pushed. If a toggle button is currently pushed in or not is usually hard to tell.

EDM, MEDM, BOY, .. had separate widgets for these, just like FXSceneBuilder, Qt Designer.

So no, it's fine to keep the Action Button, Boolean Button, CheckBox, Radio Button, .. as separate Widgets.
Doesn't mean that they can share more code, like the confirmation handling that you suggest in #408 .
