### ISSUE TITLE
Logarithmic X scale in X/Y Plot widget

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#411]
We want to plot one waveform against another waveform.
For this we use a X/Y plot and Display Builder.
We want to have possibility to plot in the log-log scale
The log scale for Y axis we can choose from menu or from properties, what about X axis?

**Comment by kasemir** [comment]
I'll add log option to the XYPlot X axis.

**Comment by kasemir** [comment]
Try now, X axis can be set to log scale from both widget config and runtime plot config dialog

**Comment by kasemir** [comment]
The domain of the example data is 0 to 10. Unfortunately, log(0) is not defined, see https://en.wikipedia.org/wiki/Logarithm. The best I could do was work around the issue by mapping log(0) to `HUGE_NEGATIVE=-1e100`, check the `Log10` class.

Users who insist in plotting invalid data on a log axis have to manually set the axis range, as shown in this example that starts at 0.1 instead of 0.0:

![log](https://user-images.githubusercontent.com/1932421/42509330-8c15653a-8419-11e8-8832-0c2242c4aada.png)

**Comment by claudio-rosati** [comment]
What you say is clear and perfectly right. The fact remains that silly people (like me) can just check the 'log scale' button and, being no feedback is given about "not using 0 ins Start or End", remaining confused.

Maybe it is possible to set the foreground color to red in "Start" and "End" when 0 and 'log scale' is pressed.
