### ISSUE TITLE
Not clear what `autosize` should do in CheckBoxes

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#493]
Setting `autosize` to true in CheckBox widgets doesn't change anything in the representation and/or in the behaviour.

What is it meant to do?

**Comment by kasemir** [comment]
Looks like the property was added because it's found in the BOY widget, but functionality was never implemented.
Should function like the Label.autosize, adjusting width based on the size of Checkbox.label.
Checkbox.label doesn't currently allow entering a newline into the text, so the checkbox label is always single-line, and the Checkbox.height should probably just autosize to the height of the checkbox square.
