### ISSUE TITLE
ComboBox widget problem

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#520]
Clicking on a combo for the first time when in edit mode opens the drop-down menu and makes Display Builder think the display has changed, marking it as "to be saved".

After a save, the problem doesn't appear anymore.

**Comment by kasemir** [comment]
I see that the drop-down briefly opens, but for me that doesn't change the 'dirty' state of the editor.

Also not sure how to prevent the combo from opening.
In principle, there's already an event filter, `isFilteringEditModeClicks`, that captures and consumes mouse clicks. Disabling the combo in edit mode means you can't select it at all.

Only "fix" I see would be to place the combo behind some other widget, e.g. a rectangle, in edit mode, so that widget in front can then for sure capture the mouse clicks.

**Comment by claudio-rosati** [comment]
Thank you for the fix populating only at runtime.
