### ISSUE TITLE
Image ROI issue

### ISSUE THREAD

**Issue by MaticPogacnik** [kasemir/org.csstudio.display.builder#545]
Hi,

I have problem with ROI selection on Image widget. 
0 of Y axis starts on the bottom not top as it was in the opi. 
This means if you link PVs from AD ROI plugin directly to "Y PV" and "Height PV "  property you get wrong selection.
But its interesting, image is displayed correctly.
Was this done intentional?

Thank you,

![2](https://user-images.githubusercontent.com/5747624/60644828-7c75de00-9e37-11e9-9e56-a31c88e6d398.png)
![1](https://user-images.githubusercontent.com/5747624/60644829-7c75de00-9e37-11e9-8f6a-d6afc0219f2c.png)

**Comment by kasemir** [comment]
The ROI PVs use the same coordinate system as the Y axis.
In your screenshot, the Y axis is configured with a minimum .. maximum of 0 .. ~1000.
If you want the 0 to be on top, swap the Y axis range to be 1000 .. 0.

**Comment by MaticPogacnik** [comment]
Yes this was the issue.
Thank you!

**Comment by kasemir** [comment]
Are these auto-converted files, like *.opi files opened in the display builder without further changes
-> Then we should update the display builder to swap the axis range accordingly

Or were these displays newly created?
-> Yes, the default is 0 at bottom for images, just like 0 is at bottom for XY plots. We had brief discussions locally about that when creating the display builder, and local users found it more natural to have the "normal" plot axis layout, not the computer science idea that images have 0 on top because that's where the memory array has index [0].
